// Authorization constants

var keyMirror = require('keymirror');

module.exports = {
  ActionTypes: keyMirror({
    SET_AUTHORIZATIONS: null
  }),
  BaseBanks: ['assessment.Bank%3AROOT%40ODL.MIT.EDU',
              'assessment.Bank%3A000000000000000000000000%40ODL.MIT.EDU',
              'assessment.Bank%3A000000000000000000000000%40bazzim.MIT.EDU'],
  InstructorAuthorizationFunctions: ['assessment.Assessment%3Aauthor%40ODL.MIT.EDU',
                                     'assessment.Assessment%3Acreate%40ODL.MIT.EDU',
                                     'assessment.Assessment%3Adelete%40ODL.MIT.EDU',
                                     'assessment.Assessment%3Alookup%40ODL.MIT.EDU',
                                     'assessment.Assessment%3Asearch%40ODL.MIT.EDU',
                                     'assessment.Assessment%3Atake%40ODL.MIT.EDU',
                                     'assessment.Assessment%3Aupdate%40ODL.MIT.EDU',
                                     'assessment.AssessmentOffered%3Acreate%40ODL.MIT.EDU',
                                     'assessment.AssessmentOffered%3Adelete%40ODL.MIT.EDU',
                                     'assessment.AssessmentOffered%3Alookup%40ODL.MIT.EDU',
                                     'assessment.AssessmentOffered%3Aupdate%40ODL.MIT.EDU',
                                     'assessment.AssessmentResults%3Aaccess%40ODL.MIT.EDU',
                                     'assessment.AssessmentTaken%3Acreate%40ODL.MIT.EDU',
                                     'assessment.AssessmentTaken%3Alookup%40ODL.MIT.EDU',
                                     'assessment.AssessmentTaken%3Asearch%40ODL.MIT.EDU',
                                     'assessment.Assessment%3Atake%40ODL.MIT.EDU',
                                     'assessment.Bank%3Aaccess%40ODL.MIT.EDU',
                                     'assessment.Bank%3Aalias%40ODL.MIT.EDU',
                                     'assessment.Bank%3Acreate%40ODL.MIT.EDU',
                                     'assessment.Bank%3Adelete%40ODL.MIT.EDU',
                                     'assessment.Bank%3Alookup%40ODL.MIT.EDU',
                                     'assessment.Bank%3Amodify%40ODL.MIT.EDU',
                                     'assessment.Bank%3Asearch%40ODL.MIT.EDU',
                                     'assessment.Bank%3Aupdate%40ODL.MIT.EDU',
                                     'assessment_authoring.AssessmentPart%3Acreate%40ODL.MIT.EDU',
                                     'assessment_authoring.AssessmentPart%3Adelete%40ODL.MIT.EDU',
                                     'assessment_authoring.AssessmentPart%3Alookup%40ODL.MIT.EDU',
                                     'assessment_authoring.AssessmentPart%3Aupdate%40ODL.MIT.EDU',
                                     'commenting.Book%3Alookup%40ODL.MIT.EDU',
                                     'commenting.Comment%3Alookup%40ODL.MIT.EDU',
                                     'grading.Gradebook%3Acreate%40ODL.MIT.EDU',
                                     'grading.Gradebook%3Adelete%40ODL.MIT.EDU',
                                     'grading.Gradebook%3Alookup%40ODL.MIT.EDU',
                                     'grading.Gradebook%3Aupdate%40ODL.MIT.EDU',
                                     'grading.GradeEntry%3Acreate%40ODL.MIT.EDU',
                                     'grading.GradeEntry%3Adelete%40ODL.MIT.EDU',
                                     'grading.GradeEntry%3Alookup%40ODL.MIT.EDU',
                                     'grading.GradeEntry%3Aupdate%40ODL.MIT.EDU',
                                     'grading.GradeSystem%3Acreate%40ODL.MIT.EDU',
                                     'grading.GradeSystem%3Adelete%40ODL.MIT.EDU',
                                     'grading.GradeSystem%3Alookup%40ODL.MIT.EDU',
                                     'grading.GradeSystem%3Aupdate%40ODL.MIT.EDU',
                                     'grading.GradebookColumn%3Acreate%40ODL.MIT.EDU',
                                     'grading.GradebookColumn%3Adelete%40ODL.MIT.EDU',
                                     'grading.GradebookColumn%3Alookup%40ODL.MIT.EDU',
                                     'grading.GradebookColumn%3Aupdate%40ODL.MIT.EDU',
                                     'hierarchy.Hierarchy%3Alookup%40ODL.MIT.EDU',
                                     'learning.ObjectiveBank%3Acreate%40ODL.MIT.EDU',
                                     'learning.ObjectiveBank%3Adelete%40ODL.MIT.EDU',
                                     'learning.ObjectiveBank%3Alookup%40ODL.MIT.EDU',
                                     'learning.ObjectiveBank%3Aupdate%40ODL.MIT.EDU',
                                     'learning.Proficiency%3Acreate%40ODL.MIT.EDU',
                                     'learning.Proficiency%3Adelete%40ODL.MIT.EDU',
                                     'learning.Proficiency%3Alookup%40ODL.MIT.EDU',
                                     'learning.Proficiency%3Aupdate%40ODL.MIT.EDU',
                                     'logging.Log%3Alookup%40ODL.MIT.EDU',
                                     'repository.Asset%3Acreate%40ODL.MIT.EDU',
                                     'repository.Asset%3Adelete%40ODL.MIT.EDU',
                                     'repository.Asset%3Alookup%40ODL.MIT.EDU',
                                     'repository.Asset%3Asearch%40ODL.MIT.EDU',
                                     'repository.Repository%3Alookup%40ODL.MIT.EDU',
                                     'resource.Bin%3Alookup%40ODL.MIT.EDU',
                                     'resource.Resource%3Alookup%40ODL.MIT.EDU']
};
